spring:
  application:
    name: Jorasoft
  datasource:
    url: jdbc:postgresql://localhost:5432/auralife
    username: postgres
    password: tplink01459520
    driverClassName: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: yuldashevsss2007@gmail.com
    password: nmsj nzan kdyg pqqm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

secret:
  key: ApeVFjUOyTmk7XYwgcYwIEsix1mALAsQhftYQqWHE8P6kcnqbZv0Uxj9HduKEvjXzz0sVYCG0ZjSBtmxadtAiQ==


server:
  port: 20007


api:
  url: http://localhost:20007
  photoUrl: http://localhost:20007/photo/get
  photo-save-path: src/main/resources/images/